#! /bin/sh
set -e
./Configure PlanC android
make
mkdir -p ~/release
install -m 0554 make_release ~/release
cd ~/release
./make_release
echo "Copying result apk to /var/tmp  for easy upload"
cp -pav $(ls -tr *.apk|tail -1) /var/tmp
